name: Run Ruff

on:
  push:
    branches:
      - '!main'

jobs:
  ruff_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ruff check
        uses: astral-sh/ruff-action@v1
